DataQualityGateway/src/java/dataqualitygateway/dto/Result.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dataqualitygateway.dto;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.LinkedList;
import java.util.List;
import java.util.Objects;
import org.bson.BsonString;
import org.bson.BsonValue;

/**
 *
 * @author SandroSchedl
 */
public class Result implements Serializable{
    private String resultId; 
    private List<GenericPojo> recordList;
    private long time;
    private Template template;
    private String fileName;
    private LocalDateTime date;
    private int recordCnt;
    private int anzCorrectRecords;
    private int anzRecordsWithOneError;
    private int anzRecordsWithMoreErrors;

    public Result() {
    }

    public Result(Template t, String fileName) {
        this(t,fileName,0,0,0,0,true);
    }

    public Result(Result currentResult) {
        this(currentResult.getTemplate(),
                currentResult.getFileName(),
                currentResult.getTime(),
                currentResult.getAnzCorrectRecords(),
                currentResult.getAnzRecordsWithOneError(),
                currentResult.getAnzRecordsWithMoreErrors(),
                false);
        this.recordList = new LinkedList<>(currentResult.getRecordList());
        this.resultId = currentResult.getResultId();
        this.template = new Template(this.getTemplate());
    }
    
    public String getFormattedTimeStamp(){
        if(date != null){
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd' 'HH:mm:ss");
        return date.format(dtf);
        }
        return "";
    }
    
    

    public Result(Template template, String fileName, long time, int anzCorrectRecords, int anzRecordsWithOneError, int anzRecordsWithMoreErrors, boolean setResultId) {
        this.time = time;
        this.template = template;
        this.fileName = fileName;
        this.anzCorrectRecords = anzCorrectRecords;
        this.anzRecordsWithOneError = anzRecordsWithOneError;
        this.anzRecordsWithMoreErrors = anzRecordsWithMoreErrors;
        this.date = LocalDateTime.now();
        if(setResultId)
            resultId = template.getName() + "temp_" + template.increaseAndGetLastId();
        System.out.println("TEMPLATE ID: " + template.getLastId());
        recordList = new LinkedList<>();
    }
    
        
    public BsonValue getResultIdAsBsonValue() {
        return new BsonString(resultId);
    }

    public LocalDateTime getDate() {
        return date;
    }

    public void setDate(LocalDateTime date) {
        this.date = date;
    }
    
    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
    
    public int getPercentageOfAll(int anz){
        return anz * 100 / (this.anzCorrectRecords + this.anzRecordsWithMoreErrors + this.anzRecordsWithOneError );
    }

    public int getAnzCorrectRecords() {
        return anzCorrectRecords;
    }

    public void setAnzCorrectRecords(int anzCorrectRecords) {
        this.anzCorrectRecords = anzCorrectRecords;
    }

    public int getAnzRecordsWithOneError() {
        return anzRecordsWithOneError;
    }

    public void setAnzRecordsWithOneError(int anzRecordsWithOneError) {
        this.anzRecordsWithOneError = anzRecordsWithOneError;
    }

    public int getAnzRecordsWithMoreErrors() {
        return anzRecordsWithMoreErrors;
    }

    public void setAnzRecordsWithMoreErrors(int anzRecordsWithMoreErrors) {
        this.anzRecordsWithMoreErrors = anzRecordsWithMoreErrors;
    }

    public List<GenericPojo> getRecordList() {
        return recordList;
    }

    public void setRecordList(List<GenericPojo> recordList) {
        this.recordList = recordList;
    }

    public int getRecordCnt() {
        return recordCnt;
    }
    
    public int increaseAndGetRecordCnt(){
        return ++recordCnt;
    }

    public void setRecordCnt(int recordCnt) {
        this.recordCnt = recordCnt;
    }

    public long getTime() {
        return time;
    }

    public void setTime(long time) {
        this.time = time;
    }

    public Template getTemplate() {
        return template;
    }

    public void setTemplate(Template template) {
        this.template = template;
    }

    public String getResultId() {
        return resultId;
    }

    public void setResultId(String resultId) {
        this.resultId = resultId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Result other = (Result) obj;
        
        return Objects.equals(this.resultId, other.resultId);
    }

    public void setStatistics(long time, int perf, int oneWrong, int wrong) {
        this.time = time;
        this.anzCorrectRecords = perf;
        this.anzRecordsWithOneError = oneWrong;
        this.anzRecordsWithMoreErrors = wrong;
    }



    
}

DataQualityGateway/web/WEB-INF/templates/footer.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core"
    xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:p="http://primefaces.org/ui">

    <div class="layout-footer">
        <h:link outcome="/ruleScreen" styleClass="logo-container">
            <p:graphicImage name="images/harmony-logo.png" library="harmony-layout" />
            <span class="app-name">HARMONY</span>
        </h:link>

        <div class="footer-icons">
            <ul>
                <li>
                    <a>
                        <i class="fa fa-twitter"></i>
                    </a>
                </li>
                <li>
                    <a>
                        <i class="fa fa-facebook"></i>
                    </a>
                </li>
                <li>
                    <a>
                        <i class="fa fa-github"></i>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</ui:composition>

DataQualityGateway/web/WEB-INF/templates/right_panel.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:p="http://primefaces.org/ui"
                xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">

    <style type="text/css">
        .logo {
            width: 5%
        }

        .detail {
            width: 95%;
            padding-left: 25px;
        }

        .detail td {
            font-size: 24px;
        }

        .ui-datascroller .ui-datascroller-item {
            border-bottom: 1px solid #A8A8A8;
            padding: 25px 10px;
            /* with the exported variables from Nova and Luna Themes*/
            border-bottom-color: var(--input-border-color, #A8A8A8);
        }

        .noHeader.ui-datatable table thead tr {
            display: none;
        }

        .ui-tabs { 
            position: relative; 
            padding: .2em; 
            zoom: 1; 
        }

        .ui-tabview {
            padding: .25em;
            text-align: center;
        }
        #help.ui-tabs.ui-tabs-top > .ui-tabs-nav {
            display: none!important;
        }

    </style>

    <div id="layout-right-panel">
        <div class="nano">
            <div class="nano-content right-panel-scroll-content">
                <h:form>
<!--                    tab for language switching-->
                    <p:tabView activeIndex="0">
                        <p:tab id="sett" title="#{bundleVar.settings}">
                            <div style="height:20px;"></div>
                            <div class="submenu-content settings">
                                <div class="ui-g">
                                    <div class="ui-g-12 ui-md-6">
                                        <div class="status-box language-status">
                                            <i class="fa fa-fw fa-globe box-icon"></i>
                                            <span class="status-name">#{bundleVar.LANGUAGE}</span>
                                            <span class="status">
                                                <p:selectOneMenu id="language" value="#{settingsBean.language}" style="width:150px">
                                                    <f:selectItems value="#{settingsBean.languages}" var="language" itemValue="#{language}" itemLabel="#{language}"/>
                                                    <p:ajax listener="#{settingsBean.switchLanguage}" update="@all"/>
                                                </p:selectOneMenu>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </div>                      
                        </p:tab>
<!--                        tab for previous results-->
                        <p:tab id="che" title="#{bundleVar.checks}">
                            <div class="submenu-content notes">
                                <p:dataScroller value="#{service.lastResults}" var="check" chunkSize="10">
                                    <f:facet name="header">
                                        <p:outputLabel value="#{bundleVar.lastChecks}" style="font-weight:bold;font-size:16px;color:black;"/>
                                    </f:facet>

                                    <h:panelGrid columns="1" style="width:100%" columnClasses="logo,detail">
                                        <p:commandLink update="@all" action="#{fileUploadBean.changeResult(check)}" style="margin-right:20px;color:black;">
                                            <h:outputLabel value="File: #{check.fileName}" style="font-weight:bold;font-size:16px;"/>
                                        </p:commandLink>

                                        <p:outputLabel id="time" value="#{check.formattedTimeStamp}" style="font-size:16px;" />
                                        
                                        <p:outputPanel>
                                            <p:dataTable styleClass="noHeader" var="check" value="#{check}" tableStyle="width:auto">
                                                <p:column style="background-color:#74B23D;text-align:center;width:#{check.getPercentageOfAll(check.anzCorrectRecords)}%">
                                                    <h:outputText value="#{check.getPercentageOfAll(check.anzCorrectRecords)}%" />
                                                </p:column>

                                                <p:column style="background-color:#FFC400;text-align:center;width:#{check.getPercentageOfAll(check.anzRecordsWithOneError)}%">
                                                    <h:outputText value="#{check.getPercentageOfAll(check.anzRecordsWithOneError)}%" />
                                                </p:column>

                                                <p:column style="background-color:#cc0000;text-align:center;width:#{check.getPercentageOfAll(check.anzRecordsWithMoreErrors)}%">
                                                    <h:outputText value="#{check.getPercentageOfAll(check.anzRecordsWithMoreErrors)}%"/>
                                                </p:column>

                                            </p:dataTable>
                                        </p:outputPanel>
                                    </h:panelGrid>
                                </p:dataScroller>
                            </div>
                        </p:tab>   
<!--                        tab for quote of the day-->
                        <p:tab id="help" title="#{bundleVar.qotd}">
                            <div style="height:20px;"></div>
                            <div class="submenu-content qotd">
                                <div class="ui-g">
                                    <div class="ui-g-12 ui-md-6">
                                        <div class="status-box qotd-status">
                                            <i class="fa fa-fw fa-gift box-icon"></i>
                                            <span class="status-name">#{bundleVar.quoteOfTheDay}</span>
                                            <span class="status">
                                                <p:outputPanel deferred="true">
                                                    <h3>#{dashboardView.quoteOfTheDay}</h3>
                                                </p:outputPanel>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </div>  
                        </p:tab>
                    </p:tabView>

                </h:form>

                <div class="nano-scroll-footer" />
            </div>
        </div>
    </div>
</ui:composition>

DataQualityGateway/web/WEB-INF/templates/routebar-menu.xhtml
<ui:composition
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:p="http://primefaces.org/ui">

    <ul class="route-bar-menu">
        <li>
            <a href="#">
                <i class="fa fa-asterisk" />
                <span>Overview</span>
            </a>
        </li>
        <li>
            <a href="#">
                <i class="fa fa-paper-plane" />
                <span>Demos</span>
            </a>
        </li>
        <li>
            <a href="#">
                <i class="fa fa-file-code-o" />
                <span>Documentation</span>
            </a>
        </li>
        <li>
            <a href="#">
                <i class="fa fa-life-saver" />
                <span>Support</span>
            </a>
        </li>
        <li>
            <a href="#">
                <i class="fa fa-user" />
                <span>Profile</span>
            </a>
        </li>
    </ul>

    <p:tooltip globalSelector=".route-bar-menu a" position="bottom" showDelay="0"/>

</ui:composition>

DataQualityGateway/web/WEB-INF/templates/sidebar.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml" 
                xmlns:h="http://java.sun.com/jsf/html" 
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets" 
                xmlns:p="http://primefaces.org/ui"
                xmlns:ph="http://primefaces.org/harmony">

    <div class="layout-sidebar">
        <div class="nano">
            <div class="nano-content menu-scroll-content">
                <h:form id="menuform">
                    <ui:insert name="sideBar1" ></ui:insert>

                    <p:poll interval="10" process="@form" update="@form" stop="#{fileUploadBean.displayMessageOnStop()}" />

                    <h:form id="DBForm" rendered="#{fileUploadBean.isDatabaseInProcess()}">

                        <a style="display: block; text-align: center; color:  black" >
                            <i id="DBIcon" class="fa fa-fw fa-database" />
                            <span style="font-weight: bold; font-size: larger;" >Database Progress:</span>
                        </a>
                        <br/>
                        <p:progressBar  id="dataBaseProgressBar" style="height:6px; width: 90%; margin-left: 5%" 
                                       mode="indeterminate" widgetVar="dataBaseProgressBar" />

                    </h:form>
                </h:form>
            </div>
        </div>
    </div>
</ui:composition>

DataQualityGateway/web/WEB-INF/templates/template.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      lang="en">
    <f:view contentType="text/html" locale="#{localeBean.userLoc}">
        <h:head>      
            <f:facet name="first">
                <meta http-equiv="X-UA-Compatible" content="IE=edge" />
                <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
                <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"/>
                <meta name="apple-mobile-web-app-capable" content="yes" />
            </f:facet>
            <title><ui:insert name="title">PrimeFaces harmony</ui:insert></title>
            <h:outputScript name="js/nanoscroller.js" library="harmony-layout" />
            <h:outputScript name="js/layout.js" library="harmony-layout" />
            <ui:insert name="head"/>
        </h:head>

        <h:body>
            <div class="layout-wrapper layout-menu-static">
                <ui:insert name="topbar">
                    <ui:include src="./topbar.xhtml" />
                </ui:insert>
                <ui:insert name="rightPanel">
                    <ui:include src="./right_panel.xhtml" />
                </ui:insert>
                <ui:insert name="sideBar">
                    <ui:include src="./sidebar.xhtml" />
                </ui:insert>
                <div class="layout-main">
                    <div class="route-bar">

                        <ui:insert name="routeBar">

                        </ui:insert>
                    </div>

                    <div class="layout-content">
                        <ui:insert name="content"></ui:insert>
                    </div>



                    <div class="layout-mask"></div>
                </div>
            </div>

            <p:ajaxStatus style="width:32px;height:32px;position:fixed;right:7px;bottom:7px">
                <f:facet name="start">
                    <i class="fa fa-2x fa-circle-o-notch fa-spin ajax-status-icon" aria-hidden="true"></i>
                </f:facet>

                <f:facet name="complete">
                    <h:outputText value="" />
                </f:facet>
            </p:ajaxStatus>

            <h:outputStylesheet name="css/nanoscroller.css" library="harmony-layout" />
            <h:outputStylesheet name="css/layout-vanity.css" library="harmony-layout" />

        </h:body>

    </f:view>

</html>

DataQualityGateway/web/WEB-INF/templates/topbar.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core"
    xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:p="http://primefaces.org/ui">

    <div class="layout-topbar">
        <h:link outcome="/ruleScreen" styleClass="logo-container">
            <p:graphicImage name="images/raikaB_1.png" library="harmony-layout" />
            <span class="app-name">DQG</span>
        </h:link>

        <div class="topbar-content">
            <a href="#" id="topbar-sidebar-button">
                <i class="fa fa-bars"></i>
            </a>
           <ui:insert name="topBar1"></ui:insert>

            <a href="#" id="topbar-quickmenu-button">
                QUICK MENU
            </a>

            
            <a id="topbar-right-panel-button" href="#">
                <i class="fa fa-ellipsis-v"></i>
            </a>
           

            <ul id="topbar-profile-menu">
                <li>
                    <a href="#">
                        <i class="topbar-icon fa fa-fw fa-paint-brush"></i>
                        <span class="topbar-item-name">Change Theme</span>
                    </a>
                    <ul>
                        <li role="menuitem">
                            <a href="#">
                                <i class="fa fa-fw fa-moon-o"></i>
                                <span>Dark Topbar</span>
                            </a>
                        </li>
                        <li role="menuitem">
                            <a href="#">
                                <i class="fa fa-fw fa-sun-o"></i>
                                <span>Light Topbar</span>
                            </a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#">
                        <i class="topbar-icon fa fa-fw fa-heart"></i>
                        <span class="topbar-item-name">Favorites</span>
                    </a>
                    <ul>
                        <li role="menuitem">
                            <a href="#">
                                <i class="fa fa-fw fa-paint-brush"></i>
                                <span>Change Theme</span>
                            </a>
                        </li>
                        <li role="menuitem">
                            <a href="#">
                                <i class="fa fa-fw fa-star-o"></i>
                                <span>Favorites</span>
                            </a>
                        </li>
                        <li role="menuitem">
                            <a href="#">
                                <i class="fa fa-fw fa-lock"></i>
                                <span>Lock Screen</span>
                            </a>
                        </li>
                        <li role="menuitem">
                            <a href="#">
                                <i class="fa fa-fw fa-picture-o"></i>
                                <span>Wallpaper</span>
                            </a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#">
                        <i class="topbar-icon material-icons animated swing fa fa-fw fa-lock"></i>
                        <span class="topbar-item-name">Lock Screen</span>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="topbar-icon fa fa-fw fa-picture-o"></i>
                        <span class="topbar-item-name">Wallpaper</span>
                    </a>
                    <ul>
                        <li role="menuitem">
                            <a href="#">
                                <i class="fa fa-fw fa-tasks"></i>
                                <span>Pending tasks</span>
                            </a>
                        </li>
                        <li role="menuitem">
                            <a href="#">
                                <i class="fa fa-fw fa-calendar-check-o"></i>
                                <span>Meeting today</span>
                            </a>
                        </li>
                        <li role="menuitem">
                            <a href="#">
                                <i class="fa fa-fw fa-download"></i>
                                <span>Download</span>
                            </a>
                        </li>
                        <li role="menuitem">
                            <a href="#">
                                <i class="fa fa-fw fa-plane"></i>
                                <span>Book flight</span>
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>

        </div>
    </div>

</ui:composition>