DataQualityGateway/src/java/dataqualitygateway/dto/Column.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dataqualitygateway.dto;

import dataqualitygateway.dto.enums.Rule;
import dataqualitygateway.dto.enums.DataType;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.bson.BsonArray;
import org.bson.BsonDocument;
import org.bson.BsonElement;
import org.bson.BsonInt32;
import org.bson.BsonNull;
import org.bson.BsonString;
import org.bson.BsonType;
import org.bson.BsonValue;

/**
 *
 * @author SandroSchedl
 */
public class Column extends SelectToRule implements HasPDFValue, Serializable {

    private String name;
    private DataType dataType;
    private CustomizedRule customRule;
    private List<SelectGroup> groupList;
    private List<GenericPojo> compareList = new LinkedList<>();
    

    public Column(String name) {
        this.name = name;
        this.dataType = DataType.STRING;
        this.chooserList = newChooserList(Rule.getRules());
        this.groupList = new LinkedList<>();
//        ruleList.add(Rule.ATSIGN);
//        ruleList.add(Rule.CAPSCHECKER);
//        ruleList.add(Rule.CREDITCARDCHECKER);
//        ruleList.add(Rule.DATECHECKER);
//        ruleList.add(Rule.ISCOUNTRY);
    }

    public BsonElement getColumnAsBsonObject() {
        return new BsonElement(name, new BsonDocument("dataType", new BsonString(dataType.getName()))
                .append("ruleList", getRulesAsBsonArray())
                .append("customRule", getCustomRuleAsBsonObject()));

    }

    public void addSelectGroup(SelectGroup sg) {
        this.groupList.add(sg);
    }

    private BsonValue getCustomRuleAsBsonObject() {
        if (customRule != null) {
            return customRule.getAsBsonDocument();
        }

        return new BsonNull();
    }

    @Override
    public String getPDFValue() {
        return name;
    }

    @Override
    public boolean isValueCorrect() {
        return true;
    }

    public CustomizedRule getCustomRule() {
        return customRule;
    }

    public void setCustomRule(CustomizedRule customRule) {
        this.customRule = customRule;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public DataType getDataType() {
        return dataType;
    }

    public void setDataType(DataType type) {
        this.dataType = type;
    }

    @Override
    public String toString() {
        return "Column{" + "name=" + name + ", type=" + dataType + '}';
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 71 * hash + Objects.hashCode(this.name);
        return hash;
    }

    public List<Select> getChooserList() {
        return chooserList;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Column other = (Column) obj;
        return Objects.equals(this.name, other.name);
    }

    public void setChooserList(List<Select> chooserList) {
        this.chooserList = chooserList;
    }

    public List<Select> newChooserList(List<Rule> ruleList) {
        List<Select> selList = new ArrayList<>();
        for (Rule r : ruleList) {
            selList.add(new Select(r, false));
        }
        return selList;
    }

    public List<SelectGroup> getGroupList() {
        return groupList;
    }

    public void setGroupList(List<SelectGroup> grList) {

        this.groupList = grList;
//         else {
//            for (SelectGroup gr : groupList) {
//                for (SelectGroup newGr : grList) {
//                    this.groupList.add(newGr);
//                    if (gr.getG().getGroupId() == newGr.getG().getGroupId()) {
//                        this.groupList.remove(newGr);
//                    }
//                }
//            }
//        }

    }

    public List<Select> getShowChooserList() {
        List<Select> retValList = new LinkedList<>();

        for (Select s : this.chooserList) {
            if (s.isChooser()) {
                retValList.add(s);
            }
        }
        return retValList;
    }

    public List<SelectGroup> getShowGroupList() {
        List<SelectGroup> retValList = new LinkedList<>();

        for (SelectGroup gs : this.groupList) {
            if (gs.isChooser()) {
                retValList.add(gs);
            }
        }
        return retValList;
    }

    public List<GenericPojo> getCompareList() {
        return compareList;
    }

    public void setCompareList(List<GenericPojo> compareList) {
        this.compareList = compareList;
    }
     

}

DataQualityGateway/src/java/dataqualitygateway/dto/SelectToRule.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dataqualitygateway.dto;

import dataqualitygateway.dto.enums.Rule;
import java.io.Serializable;
import java.util.LinkedList;
import java.util.List;
import org.bson.BsonArray;
import org.bson.BsonInt32;

/**
 *
 * @author SandroSchedl
 */
public class SelectToRule implements Serializable{
        
    protected List<Select> chooserList;
    
    public List<Rule> getRules() {
        List<Rule> ruleList = new LinkedList<>();
        for (Select s : chooserList) {
            if (s.isChooser()) {
                ruleList.add(s.getR());
            }
        }

        return ruleList;
    }

    public void setRules(List<Integer> ruleIdList) {

        chooserList.forEach((s) -> {
            s.setChooser(false);
            for (int id : ruleIdList) {
                if (id == s.getR().getId()) {
                    s.setChooser(true);
                }
            }
        });
    }

    protected BsonArray getRulesAsBsonArray() {
        BsonArray retVal = new BsonArray();

        for (Rule r : getRules()) {
            retVal.add(new BsonInt32(r.getId()));
        }

        return retVal;
    }
}

DataQualityGateway/src/java/dataqualitygateway/presentation/RuleScreenBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dataqualitygateway.presentation;

import dataqualitygateway.dto.Column;
import dataqualitygateway.dto.CustomizedRule;
import dataqualitygateway.dto.RuleHelper;
import dataqualitygateway.service.Service;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;

/**
 *
 * @author max
 */
@ManagedBean
@SessionScoped
public class RuleScreenBean {

    @ManagedProperty(value = "#{service}")
    private Service service;

    //Variablen für die ValueRange Prüfung
    private int valueRangeLeft, valueRangeRight;

    //Liste für alle Länder auf English
    private List<String> countryList = initalizeCountries();

    //Liste für alle Datumsformate
    private List<String> dateList = initalizeDateList();

    //Variablen die Informationen für die Prüfregeln speichern
    private String country;
    private String bannedWords;
    private String dateFormat;
    private String parameter;

    public int getValueRangeLeft() {
        return valueRangeLeft;
    }

    public void setValueRangeLeft(int valueRangeLeft) {
        this.valueRangeLeft = valueRangeLeft;
    }

    public int getValueRangeRight() {
        return valueRangeRight;
    }

    public void setValueRangeRight(int valueRangeRight) {
        this.valueRangeRight = valueRangeRight;
    }

    private List<String> initalizeCountries() {
        RuleHelper c = new RuleHelper();
        List<String> list = new ArrayList<>();
        for (String countryCode : c.getCountries()) {

            Locale obj = new Locale("en", countryCode);
            list.add(obj.getDisplayCountry(obj));
        }
        return list;
    }

    public List<String> getCountryList() {
        return countryList;
    }

    public void setCountryList(List<String> countryList) {
        this.countryList = countryList;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getBannedWords() {
        return bannedWords;
    }

    public void setBannedWords(String bannedWords) {
        this.bannedWords = bannedWords;
    }

    private List<String> initalizeDateList() {
        List<String> list = new ArrayList<>();
        list.add("yyyy-MM-dd");
        list.add("dd-MM-yyyy");
        list.add("dd-MM-yy");

        return list;
    }

    public List<String> getDateList() {
        return dateList;
    }

    public void setDateList(List<String> dateList) {
        this.dateList = dateList;
    }

    public String getDateFormat() {
        return dateFormat;
    }

    public void setDateFormat(String dateFormat) {
        this.dateFormat = dateFormat;
    }

    public String getParameter() {
        return parameter;
    }

    public void setParameter(String parameter) {
        this.parameter = parameter;
    }

//    public void saveCustomizedRules(Column c) {
//        if (!(country == null)) {
//            service.fillCusomList(new CustomizedRule(valueRangeLeft, valueRangeRight, country, bannedWords, dateFormat, parameter, c));
//        }
//    }

    public Service getService() {
        return service;
    }

    public void setService(Service service) {
        this.service = service;
    }

}

DataQualityGateway/web/dashboard.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/templates/template.xhtml"
                xmlns:ph="http://primefaces.org/harmony"
                >
    <ui:define name="title">
        DataQualityGateWay
    </ui:define>

    <ui:define name="head">
        <h:outputScript>
            function chartExtender(){
            //this = chart widget instance
            //this.cfg = options
            this.cfg.text = 'Hallo',
            this.cfg.grid = {
            background: '#FFF',
            borderWidth: 0,
            shadow: false,
            drawGridLines: false
            };
            }

            function lineExtender() {					      
            this.cfg.seriesDefaults = {
            showMarker: false,	  
            markerOptions: {
            show: false,
            size: 20
            }
            }
            }

            function skinBar() {
            this.cfg.shadow = false;
            this.cfg.grid = {
            background: '#ffffff',
            <!--            borderColor: '#000000',-->
            <!--            gridLineColor: '#F5F5F5',-->
            shadow: false
            };
            this.cfg.seriesDefaults = {
            shadow: false,
            lineWidth: 2,
            margin: 15,
            renderer: $.jqplot.BarRenderer,
            markerOptions: {
            shadow: false,
            size: 7,
            style: 'circle'
            }
            }
            this.cfg.seriesDefaults.rendererOptions = {
            barWidth : 80
            };
            }
        </h:outputScript>

    </ui:define>

    <ui:define name="sideBar1">
        <ph:menu widgetVar="me">
            <p:submenu id="om_dashboard" expanded="true" style="background-color: #f7d5b4;" label="Dashboard" icon="fa fa-fw fa-dashboard">
                <p:menuitem rendered="true" id="om_filename" value="File: #{dashboardView.result.fileName}" disabled="true" style="font-weight:bold;color:#9e5104;"/>
            </p:submenu>
            <p:menuitem id="om_details" value="Details" icon="fa fa-info" outcome="/detailScreen.xhtml"/>
            <p:menuitem id="om_ruleGenerator" value="Rule Generator" icon="fa fa-spinner" outcome="/index.xhtml" />
        </ph:menu>

    </ui:define>

    <ui:define name="content">
        <style type="text/css">
            .ui-panel, div.ui-state-hover {
                margin: 10px;
                width:95%;
            }

            .ui-dashboard-column {
                width:25%;
                padding-bottom: 0px;
            }

        </style>

        <div style="width:100%;height:100%">
            <h:form id="dashboard">
                <p:growl id="msgs" showDetail="true" >
                    <p:autoUpdate />
                </p:growl>

                <p:dashboard id="board" model="#{dashboardView.model}" style="text-align:center;">
                    <p:panel id="records" header="#{bundleVar.records}">
                        <h:outputText value="#{dashboardView.result.recordList.size()}" />
                    </p:panel>

                    <p:panel id="correct" header="#{bundleVar.correct}">
                        <h:outputText value="#{dashboardView.result.anzCorrectRecords}" />
                    </p:panel>

                    <p:panel id="incorrect" header="#{bundleVar.incorrect}">
                        <h:outputText value="#{dashboardView.anzIncorrectRecords}"  />
                    </p:panel>

                    <p:panel id="duration" header="#{bundleVar.duration}">
                        <h:outputText value="#{dashboardView.duration}" />
                    </p:panel>           

                    <p:panel id="donutChart" header="#{bundleVar.pieChart}" style="width:195%;text-align:left;">
                            <p:chart type="donut" responsive="true" model="#{dashboardView.donutModel}" style="width:100%;height:300px;"/>
                    </p:panel>
                    
                    <p:panel id="platzhalter" collapsed="true"/>

                    <p:panel id="barChart" header="#{bundleVar.barChart}" style="width:195%;text-align:left;">
                        <p:chart type="bar" responsive="true" model="#{dashboardView.barChart}" style="width:100%;margin-left:7px;margin-right:5px;height:300px;" /> 
                    </p:panel>

                    <p:panel id="graph" header="#{bundleVar.graph}" style="width:395%;text-align:left;">
                        <p:chart type="line" rendered="true" responsive="true" model="#{dashboardView.lineModel}" style="width:100%;margin-left:7px;margin-right:5px;height:300px;" /> 
                    </p:panel>

                </p:dashboard>

            </h:form>
        </div>

    </ui:define>


</ui:composition>

DataQualityGateway/web/detailScreen.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/templates/template.xhtml"
                xmlns:ph="http://primefaces.org/harmony"
                xmlns:pe="http://primefaces.org/ui/extensions">

    <ui:define name="title">
        DetailScreen
    </ui:define>

    <ui:define name="sideBar1">
        <ph:menu widgetVar="me">
            <p:menuitem id="om_details" style="background-color: #f7d5b4;" disabled="true" value="Details" icon="fa fa-info" outcome="/detailScreen.xhtml"/>
            <p:menuitem id="om_dashboard"  value="Dashboard" icon="fa fa-fw fa-dashboard" outcome="/dashboard.xhtml" />
            <p:menuitem id="om_ruleGenerator" value="Rule Generator" icon="fa fa-spinner" outcome="/index.xhtml" />
        </ph:menu>

    </ui:define>

    <ui:define name="content">


        <h:form id="form">

            <p:growl id="messages" showDetail="true" >
                <p:autoUpdate/>
            </p:growl>


            <p:dataTable id="resultTable" widgetVar="resultTable" var="record" filteredValue="#{detailBean.filteredList}" value="#{detailBean.recordList}"
                         paginatorTemplate="{CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {Exporters}"
                         paginator="true" rows="25">
                <f:facet name="{Exporters}">
                    <div style="float: right;margin: 1px;">

                        <h:commandLink>
                            <p:graphicImage name="images/PDFLogo.png" width="24"  library="harmony-layout"/>
                            <p:fileDownload value="#{detailBean.downloadPDF()}"/>
                        </h:commandLink>

                    </div>
                </f:facet>

                <p:column exportable="false" style="width:42px" >
                    <p:rowToggler />
                </p:column>

                <p:column filterBy="#{record}" filterFunction="#{detailBean.ruleFilter}">
                    <f:facet name="header">
                        <h:outputText value="#{bundleVar.record}" style="font-size: large; font-weight: bold"/>
                        <br/>
                        <p:selectOneMenu  onchange="PF('resultTable').filter()" converter="ruleConverter" value="#{detailBean.filteredRule}" 
                                          valueChangeListener="#{detailBean.filteredRuleListener}">
                            <f:selectItem itemLabel="#{bundleVar.selectRule}" itemValue="#{null}" noSelectionOption="true"/>
                            <f:selectItems value="#{detailBean.ruleList}"/>
                        </p:selectOneMenu>
                    </f:facet>

                    <f:facet name="filter">
                        <p:selectOneButton onchange="PF('resultTable').filter()" value="#{detailBean.ruleCorrect}" valueChangeListener="#{detailBean.stateOfRuleListener}">
                            <f:selectItem itemLabel="#{bundleVar.all}" itemValue="#{null}" noSelectionOption="true"/>
                            <f:selectItem itemLabel="#{bundleVar.correct}" itemValue="#{true}"/>
                            <f:selectItem itemLabel="#{bundleVar.incorrect}" itemValue="#{false}"/>
                        </p:selectOneButton>
                    </f:facet>

                    <h:outputText value="#{record.values}" />
                </p:column>

                <p:column filterBy="#{detailBean.isRecordCorrect(record)}" width="350" style="font-size: large; font-weight: bold">
                    <f:facet name="header">
                        #{bundleVar.result}
                    </f:facet>
                    <f:facet name="filter" >
                        <p:selectOneButton onchange="PF('resultTable').filter()" value="#{detailBean.resultCorrect}" valueChangeListener="#{detailBean.stateOfResultListener}">
                            <f:converter converterId="javax.faces.Boolean" />
                            <f:selectItem itemLabel="#{bundleVar.all}" itemValue="#{null}"/>
                            <f:selectItem itemLabel="#{bundleVar.correct}" itemValue="#{true}" />
                            <f:selectItem itemLabel="#{bundleVar.incorrect}" itemValue="#{false}" />
                        </p:selectOneButton>
                    </f:facet>
                    <p:graphicImage style="display: block; margin: 0px auto;" name="#{detailBean.getResultImage(record)}" library="harmony-layout" />
                </p:column>

                <p:rowExpansion id="rowExpansion">
                    <br/>
                    <p:dataTable  id="ruleTable" widgetVar="ruleTable" value="#{detailBean.getColumnListWithRules()}" var="column" >
                        <p:column headerText="#{bundleVar.attribute}">
                            <div style="white-space: pre-wrap">
                                <h:outputText value="#{column.name}: #{record.getDetailMessage(column)}" />
                            </div>
                        </p:column>
                        <p:column headerText="#{bundleVar.rules}">
                            <div style="white-space: pre-line">
                                <h:outputText value="#{detailBean.getRuleBooleanMap(record,column)}" />
                            </div>
                        </p:column>

                    </p:dataTable>

                    <br/>
                </p:rowExpansion>

            </p:dataTable>

        </h:form>
    </ui:define>


</ui:composition>

DataQualityGateway/web/empty.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/templates/template.xhtml">
                
    <ui:define name="title">Empty Page</ui:define>
    <ui:define name="viewname">
        <li>Pages</li>
        <li>/</li>
        <li><p:link outcome="/empty">Empty</p:link></li>
    </ui:define>

    <ui:define name="content">
        <div class="ui-g">
            <div class="ui-g-12">
                <div class="card">
                    <h1>Empty Page</h1>
                    <p>Use this page to start from scratch and place your custom content.</p>
                    <p:button outcome="dashboard" value="Home" style="display:inline-block;margin-top:6px" icon="fa fa-home"/>
                </div>
            </div>
        </div>
        
    </ui:define>

</ui:composition>

DataQualityGateway/web/template.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/templates/template.xhtml"
                xmlns:ph="http://primefaces.org/harmony">

    <ui:define name="title">
        Template Screen
    </ui:define>

    <ui:define name="sideBar1">
        <ph:menu widgetVar="me">
            <p:submenu  label="Rule Generator" id="om_ruleGenerator"   icon="fa fa-spinner"  >
                <p:menuitem id="om_home" value="Rule Generator"   icon="fa fa-spinner"  outcome="/index"/>
                <p:menuitem id="om_groups" value="Groups" icon="fa fa-fw fa-cog"  outcome="/groupScreen.xhtml" />
                <p:menuitem id="om_template" value="Templates" icon="fa fa-fw fa-cog" outcome="/index" style="background-color: #f7d5b4;"/>

            </p:submenu>
        </ph:menu>

    </ui:define>
    <ui:define name="content">
        <h:form>
            <p:growl id="messages" showDetail="true" >
                <p:autoUpdate/>
            </p:growl>
            <p:dataTable var="temp" value="#{fileUploadBean.templateList}">
                <f:facet name="header">
                   <h:outputText value= "#{bundleVar.expandGroup}"></h:outputText>
                </f:facet>
                <p:column style="width:56px">
                    <p:rowToggler />
                </p:column>
                <p:column headerText="Name">
                    <h:outputText value="#{temp.name}" />
                </p:column>

                <p:rowExpansion>

                    <p:dataTable id="templateTable" value="#{fileUploadBean.setTemplateColumnList(temp.name)}" var="c" >
                        <p:column headerText="#{bundleVar.rulesAndGroups}" style="width:86px">
                            <p:rowToggler />
                        </p:column>

                        <p:column headerText="#{bundleVar.column}">
                            <div style="white-space: pre-wrap">
                                <h:outputText value="#{c.name}" />
                            </div>
                        </p:column>




                        <p:rowExpansion >

                            <p:panelGrid columns="2">
                                <p:dataTable id="templateRTable" value="#{c.showChooserList}" var="s"  >
                                    <p:column headerText="#{bundleVar.rule}"  >      

                                        <h:outputText value="#{s.r}" />

                                    </p:column>
                                    <p:column headerText="#{bundleVar.customizedRule}"  >      

                                        <p:outputLabel value=" " rendered="#{s.r.id eq 4}"> 
                                            <h:outputText value="#{bundleVar.country}"></h:outputText>
                                            <h:outputText value="#{c.customRule.country}"></h:outputText>
                                        </p:outputLabel>
                                        <p:outputLabel value=" " rendered="#{s.r.id eq 12}"> 
                                            <h:outputText value="#{bundleVar.bannedWords}" ></h:outputText>
                                            <h:outputText value="#{c.customRule.bannedWords}"></h:outputText>
                                        </p:outputLabel>
                                        <p:outputLabel value=" " rendered="#{s.r.id eq 15}"> 
                                            <h:outputText value="#{bundleVar.dateFormat}"></h:outputText>
                                            <h:outputText value="#{c.customRule.dateFormat}"></h:outputText>
                                        </p:outputLabel>
                                        <p:outputLabel value=" " rendered="#{s.r.id eq 16}"> 
                                            <h:outputText value="#{bundleVar.parameter}"></h:outputText>
                                            <h:outputText value="#{c.customRule.parameter}"></h:outputText>
                                        </p:outputLabel>
                                        <p:outputLabel value=" " rendered="#{s.r.id eq 1}"> 
                                            <h:outputText value="#{bundleVar.valueRange}"></h:outputText>
                                            <h:outputText value="#{c.customRule.valueRangeLeft}"></h:outputText>
                                            <h:outputText value="-"></h:outputText>
                                            <h:outputText value="#{c.customRule.valueRangeRight}"></h:outputText>
                                        </p:outputLabel>
                                    </p:column>
                                </p:dataTable>

                                <p:dataTable id="templateGTable" value="#{c.showGroupList}" var="g"  >

                                    <p:column style="width:56px" >

                                        <p:rowToggler />
                                    </p:column>
                                    <p:column headerText="ID">
                                        <h:outputText value="#{g.g.groupId}" />
                                    </p:column>
                                    <p:column headerText="Name">
                                        <h:outputText value="#{g.g.groupName}" />
                                    </p:column>
                                    <p:rowExpansion>

                                        <p:dataTable id="ruleTable" value="#{g.g.groupList}" var="gss" >
                                            <p:column headerText="#{bundleVar.rule}">
                                                <div style="white-space: pre-wrap">
                                                    <h:outputText value="#{gss.r}" />
                                                </div>
                                            </p:column>
                                            <p:column headerText="#{bundleVar.customized}">
                                                  <p:outputLabel value=" " rendered="#{gss.r.id eq 4}"> 
                                <h:outputText value="#{bundleVar.country} "></h:outputText>
                                <h:outputText value="#{gss.cr.country}"></h:outputText>
                            </p:outputLabel>
                            <p:outputLabel value=" " rendered="#{gss.r.id  eq 12}"> 
                                <h:outputText value="#{bundleVar.bannedWords}"></h:outputText>
                                <h:outputText value="#{gss.cr.bannedWords}"></h:outputText>
                            </p:outputLabel>
                            <p:outputLabel value=" " rendered="#{gss.r.id  eq 15}"> 
                                <h:outputText value="#{bundleVar.dateFormat}"></h:outputText>
                                <h:outputText value="#{gss.cr.dateFormat}"></h:outputText>
                            </p:outputLabel>
                            <p:outputLabel value=" " rendered="#{gss.r.id  eq 16}"> 
                                <h:outputText value="#{bundleVar.parameter} "></h:outputText>
                                <h:outputText value="#{gss.cr.parameter}"></h:outputText>
                            </p:outputLabel>
                            <p:outputLabel value=" " rendered="#{gss.r.id  eq 1}"> 
                                <h:outputText value="#{bundleVar.valueRange} "></h:outputText>
                                <h:outputText value="#{gss.cr.valueRangeLeft}"></h:outputText>
                                <h:outputText value="-"></h:outputText>
                                <h:outputText value="#{gss.cr.valueRangeRight}"></h:outputText>
                            </p:outputLabel>
                                            </p:column>

                                        </p:dataTable>

                                    </p:rowExpansion>
                                </p:dataTable>
                            </p:panelGrid>
                        </p:rowExpansion>


                    </p:dataTable>

                </p:rowExpansion>

            </p:dataTable>


        </h:form>

    </ui:define>
</ui:composition>